name: C/C++ debug macos

on:
  push:
    branches:
      - debug_macos

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'debug_macos'
    - name: build deps & slicer
      run: ./BuildMacOS.sh -bi
    - name: tar the pack
      working-directory: ./build
      run: ls
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nightly_macos_debug.dmg
        path: build/${{ github.event.repository.name }}.dmg
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nightly_macos.tar
        path: build/${{ github.event.repository.name }}.tar
