name: C/C++ Nightly macos

on:
  push:
    branches:
      - Nigthly
      - nightly_dev
      - nightly_master
      - debug_macos

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: build deps & slicer
      run: ./BuildMacOS.sh
    - name: copy zstd
      run: cp /usr/local/opt/zstd/lib/libzstd.1.dylib ./build/pack/${{ github.event.repository.name }}/${{ github.event.repository.name }}.app/Contents/MacOS/libzstd.1.dylib
    - name: relink zstd
      run: install_name_tool -change /usr/local/opt/zstd/lib/libzstd.1.dylib  @executable_path/libzstd.1.dylib ./build/pack/${{ github.event.repository.name }}/${{ github.event.repository.name }}.app/Contents/MacOS/${{ github.event.repository.name }}
    - name: create the dmg
      run: |
        hdiutil create -ov -fs HFS+ -volname ${{ github.event.repository.name }} -srcfolder "build/pack/${{ github.event.repository.name }}" temp.dmg
        hdiutil convert temp.dmg -format UDZO -o ${{ github.event.repository.name }}.dmg
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nightly_macos.app
        path: build/pack/${{ github.event.repository.name }}/${{ github.event.repository.name }}.app
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nightly_macos.dmg
        path: ${{ github.event.repository.name }}.dmg
